const express=require('express');const http=require('http');const {Server}=require('socket.io');const Database=require('better-sqlite3');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);const db=new Database(path.join(__dirname,'ryde.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT UNIQUE NOT NULL,role TEXT NOT NULL DEFAULT 'rider',car TEXT,rating REAL DEFAULT 5,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS rides(id INTEGER PRIMARY KEY AUTOINCREMENT,rider_id INTEGER NOT NULL,driver_id INTEGER,pickup_lat REAL,pickup_lng REAL,drop_lat REAL,drop_lng REAL,pickup TEXT,dropoff TEXT,fare REAL DEFAULT 0,status TEXT DEFAULT 'searching',created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
app.use(express.json());app.use(express.static(path.join(__dirname,'../public')));
const online=new Map();
const seeds=[['Ahmed Ben Ali','+21692123456'],['Mohamed Trabelsi','+21655321987'],['Yassine Saidi','+21627456789']];for(const [name,phone] of seeds){if(!db.prepare('SELECT id FROM users WHERE phone=?').get(phone))db.prepare("INSERT INTO users(name,phone,role,car,rating) VALUES(?,?, 'driver','Toyota Corolla',4.9)").run(name,phone)}
const driverView=()=>[...online.values()].map(x=>x.driver);
app.get('/api/config',(q,s)=>s.json({city:'Gabès',currency:'TND',support:'+216'}));
app.post('/api/auth',(q,s)=>{let{name,phone,role='rider',car}=q.body||{};if(!name||!phone)return s.status(400).json({error:'Name and phone are required'});let u=db.prepare('SELECT * FROM users WHERE phone=?').get(phone);if(!u){let r=db.prepare('INSERT INTO users(name,phone,role,car) VALUES(?,?,?,?)').run(name,phone,role,car||null);u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid)}s.json(u)});
app.get('/api/users',(q,s)=>s.json(db.prepare('SELECT id,name,phone,role,car,rating,created_at FROM users ORDER BY id DESC').all()));
app.get('/api/drivers',(q,s)=>s.json(driverView()));
app.get('/api/rides',(q,s)=>s.json(db.prepare('SELECT r.*,u.name rider_name,d.name driver_name FROM rides r LEFT JOIN users u ON u.id=r.rider_id LEFT JOIN users d ON d.id=r.driver_id ORDER BY r.id DESC LIMIT 100').all()));
app.post('/api/rides',(q,s)=>{const d=q.body||{};if(!d.rider_id||d.pickup_lat==null||d.pickup_lng==null||d.drop_lat==null||d.drop_lng==null)return s.status(400).json({error:'Missing ride data'});const x=db.prepare('INSERT INTO rides(rider_id,pickup_lat,pickup_lng,drop_lat,drop_lng,pickup,dropoff,fare,status) VALUES(?,?,?,?,?,?,?,?,?)').run(d.rider_id,d.pickup_lat,d.pickup_lng,d.drop_lat,d.drop_lng,d.pickup||'Current location',d.dropoff||'Destination',Number(d.fare||0),'searching');const ride=db.prepare('SELECT * FROM rides WHERE id=?').get(x.lastInsertRowid);io.emit('ride:new',ride);s.json(ride)});
app.post('/api/rides/:id/status',(q,s)=>{const {status,driver_id}=q.body||{};const allowed=['searching','accepted','arriving','in_progress','completed','cancelled'];if(!allowed.includes(status))return s.status(400).json({error:'Invalid status'});db.prepare('UPDATE rides SET status=?,driver_id=COALESCE(?,driver_id) WHERE id=?').run(status,driver_id||null,q.params.id);const ride=db.prepare('SELECT * FROM rides WHERE id=?').get(q.params.id);io.emit('ride:update',ride);s.json(ride)});
app.post('/api/drivers/location',(q,s)=>{const d=q.body||{};if(!d.driver_id||d.lat==null||d.lng==null)return s.status(400).json({error:'Missing location'});const driver={id:d.driver_id,name:d.name,lat:d.lat,lng:d.lng,online:d.online!==false,car:d.car||'Toyota Corolla',rating:d.rating||4.9};if(driver.online)online.set(String(driver.id),{driver});else online.delete(String(driver.id));io.emit('drivers:update',driverView());s.json(driver)});
io.on('connection',socket=>{socket.emit('drivers:update',driverView());socket.on('driver:location',d=>{if(!d?.driver_id)return;online.set(String(d.driver_id),{driver:{...d,online:true}});io.emit('drivers:update',driverView())});socket.on('driver:offline',id=>{online.delete(String(id));io.emit('drivers:update',driverView())})});
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'../public/index.html')));const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log(`Ryde running on port ${PORT}`));
